# REMOVE THIS LINE! THIS IS A STUB FILE. IT WILL NOT WORK UNLESS YOU ADD A SERVICE ENTRY PER SUPPORTED GAME SERVICE. DO NOT USE THIS CONFIGURATION-FILE UNLESS YOU UNDERSTAND DOCKER / DOCKER-COMPOSE.
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile-ls-db
    ports:
      - "3453:3306"
  restapi:
    build:
      context: .
      dockerfile: Dockerfile-ls-api
    ports:
      - "4242:4242"
    depends_on:
      - database
    command: sh -c "/wait && java -jar /usr/app/ls.jar"
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
# REMOVE THIS LINE! UPDATE CONFIGURATION FOR GAME SERVICE HERE.
  foo:
    build:
      context: .
      dockerfile: ../path/to/gameservice/dockerfile
    ports:
      - "4244:4244"
    depends_on:
      - restapi
    command: sh -c "launch command for your service binary here"
version: '3.8'

